# Generated by Django 6.0.6 on 2026-07-02 04:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('projects', '0001_squashed_0003_alter_project_options'), ('projects', '0004_alter_project_options_project_slug_and_more'), ('projects', '0005_alter_project_status'), ('projects', '0006_category_alter_project_category_and_more'), ('projects', '0007_alter_project_status')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400, verbose_name='Project name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.TextField(choices=[('done', 'Done'), ('in-progress', 'In Progress')], default='in-progress', verbose_name='Status')),
                ('cost', models.PositiveBigIntegerField(verbose_name='Cost')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectcategory', verbose_name='Category')),
                ('client', models.CharField(default=1, max_length=200, verbose_name='Client')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/', verbose_name='Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Project Images',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Category name')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('done', 'تکمیل شده'), ('in-progress', 'درحال انجام')], default='in-progress', verbose_name='Status'),
        ),
    ]
