# Generated by Django 6.0.6 on 2026-07-02 04:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('projects', '0001_initial'), ('projects', '0002_alter_project_options_alter_projectcategory_options_and_more'), ('projects', '0003_alter_project_options')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400, verbose_name='Project name')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.TextField(choices=[('done', 'Done'), ('in-progress', 'In-progress')], default='in-progress', verbose_name='Status')),
                ('cost', models.PositiveBigIntegerField(verbose_name='Cost')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectcategory', verbose_name='Category')),
                ('client', models.CharField(default=1, max_length=200, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Portofilo',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/', verbose_name='Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Project Images',
            },
        ),
    ]
