# Generated by Django 6.0.5 on 2026-05-23 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default=1, max_length=200, verbose_name='Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.PositiveBigIntegerField(verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('done', 'Done'), ('in-progress', 'In-progress')], default='in-progress', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Project'),
        ),
    ]
