# Generated by Django 6.0.5 on 2026-05-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_alter_projectcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Portofilo', 'verbose_name_plural': 'Portfolios'},
        ),
    ]
