# Generated by Django 6.0.6 on 2026-06-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_project_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('done', 'Done'), ('in-progress', 'In Progress')], default='in-progress', verbose_name='Status'),
        ),
    ]
