# Generated by Django 6.0.6 on 2026-06-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_category_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('done', 'تکمیل شده'), ('in-progress', 'درحال انجام')], default='in-progress', verbose_name='Status'),
        ),
    ]
