# Generated by Django 6.0.6 on 2026-07-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_squashed_0007_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=200, verbose_name='Client'),
        ),
    ]
