[project]
name = "datis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.6",
    "django-solo>=2.5.1",
    "django-unfold>=0.98.0",
    "environs>=15.0.1",
    "pillow>=12.2.0",
    "psycopg2-binary>=2.9.12",
    "unidecode>=1.4.0",
]

[dependency-groups]
dev = [
    "faker>=40.23.0",
    "ruff>=0.15.18",
]

[tool.ruff]
line-length = 88
target-version = "py314"

exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "migrations",
    "build",
    "dist",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "SIM", # simplify
    "N",   # pep8-naming
]

ignore = [
    "E501",
]

fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true
