[project]
name = "datis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.6",
    "django-solo>=2.5.1",
    "django-unfold>=0.98.0",
    "environs>=15.0.1",
    "pillow>=12.2.0",
    "psycopg2-binary>=2.9.12",
    "unidecode>=1.4.0",
]
