# Generated by Django 6.0.5 on 2026-05-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Tagline')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('bale_url', models.URLField(blank=True, verbose_name='Bale')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('hero_title', models.CharField(blank=True, max_length=255, verbose_name='Hero title')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Hero subtitle')),
                ('hero_cta_text', models.CharField(blank=True, max_length=100, verbose_name='CTA button text')),
                ('hero_cta_link', models.CharField(blank=True, max_length=255, verbose_name='CTA link')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
