# Generated by Django 6.0.5 on 2026-05-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='working_hours',
            field=models.CharField(default=1, max_length=500, verbose_name='Working hours'),
            preserve_default=False,
        ),
    ]
