# Generated by Django 6.0.5 on 2026-05-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='working_hours',
            field=models.CharField(blank=True, max_length=500, verbose_name='Working hours'),
        ),
    ]
