# Generated by Django 6.0.6 on 2026-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_siteconfig_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='bale_url',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
    ]
