# Generated by Django 6.0.6 on 2026-07-03 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000, message='پیام شما باید کمتر از ۱۰۰۰ کاراکتر باشد')], verbose_name='Message'),
        ),
    ]
