# Generated by Django 6.0.5 on 2026-05-24 07:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Service name')),
                ('short_description', models.CharField(blank=True, help_text='Shown on the services listing page (approx. 50 characters).', max_length=200, verbose_name='Short description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first.', verbose_name='Order')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Rich text with lists, ticks, font sizes – use the WYSIWYG editor.', verbose_name='Content')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service detail',
                'verbose_name_plural': 'Service details',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Gallery images',
                'ordering': ['order'],
            },
        ),
    ]
