# Generated by Django 6.0.5 on 2026-05-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'Gallery image', 'verbose_name_plural': 'Gallery images'},
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='order',
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text with lists, ticks, font sizes – use the WYSIWYG editor.', verbose_name='Content'),
        ),
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
    ]
